# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: probes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'probes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprobes.proto\x12\x05probe\"\xaf\x01\n\x11ProbeCheckRequest\x12\x12\n\nmonitor_id\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x1c\n\x14\x65xpected_status_code\x18\x04 \x01(\x05\x12\x1d\n\x10\x65xpected_keyword\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x0ftimeout_seconds\x18\x06 \x01(\x02\x42\x13\n\x11_expected_keyword\"\x94\x01\n\x12ProbeCheckResponse\x12\x12\n\nmonitor_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x18\n\x10response_time_ms\x18\x03 \x01(\x05\x12\x12\n\nis_success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x10\n\x08probe_id\x18\x06 \x01(\t2S\n\x0cProbeService\x12\x43\n\x0c\x45xecuteCheck\x12\x18.probe.ProbeCheckRequest\x1a\x19.probe.ProbeCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'probes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROBECHECKREQUEST']._serialized_start=24
  _globals['_PROBECHECKREQUEST']._serialized_end=199
  _globals['_PROBECHECKRESPONSE']._serialized_start=202
  _globals['_PROBECHECKRESPONSE']._serialized_end=350
  _globals['_PROBESERVICE']._serialized_start=352
  _globals['_PROBESERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
