apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: uptime-monitor
data:
  nginx.conf: |
    events {}

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        sendfile on;

        upstream user_support {
            server user-support-web:8000;
        }

        upstream monitors {
            server monitors:8000;
        }

        upstream incidents {
            server incidents-web:8000;
        }

        upstream notifications {
            server notifications:8000;
        }

        server {
            listen 80;
            server_name user-support.localhost;

            location / {
                proxy_pass http://user_support;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name monitors.localhost;

            location / {
                proxy_pass http://monitors;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name incidents.localhost;

            location / {
                proxy_pass http://incidents;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name notifications.localhost;

            location / {
                proxy_pass http://notifications;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }