# Generated by Django 6.0.7 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='Sms Motification Enabled'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='telegram_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram Notification Enabled'),
        ),
    ]
