apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: uptime-monitor
type: Opaque
stringData:
  SECRET_KEY: "y-y(yi1cp1+ek-z2a50v$hue7ne931&$lgi0=7f_6lt1%fk5!u"
  DB_PASSWORD: "12345678"