apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: uptime-monitor
type: Opaque
stringData:
  EMAIL_HOST_PASSWORD: "af2wJvxZl7Wz27KAKPpY"
  TELEGRAM_BOT_TOKEN: "8695472353:AAH3R0eVG0uKVqp4VUBWLCD3WY7PI225JTg"