apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: uptime-monitor
data:
  DB_NAME: "uptimer_notifications"

  DJANGO_ALLOWED_HOSTS: "notifications.localhost,localhost,127.0.0.1"

  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"

  CSRF_TRUSTED_ORIGINS: "http://notifications.localhost"

  EMAIL_HOST: "smtp.mail.ru"
  EMAIL_PORT: "465"
  EMAIL_USE_SSL: "True"
  EMAIL_USE_TLS: "False"
  EMAIL_HOST_USER: "zhdamarovd@inbox.ru"