apiVersion: v1
kind: ConfigMap
metadata:
  name: user-support-config
  namespace: uptime-monitor
data:
  DB_NAME: "uptimer_users"

  DJANGO_ALLOWED_HOSTS: "user-support.localhost,localhost,127.0.0.1"

  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"

  CSRF_TRUSTED_ORIGINS: "http://user-support.localhost"

  USER_SUPPORT_GRPC_PORT: "50051"