# Generated by Django 6.0.7 on 2026-07-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_support", "0002_alter_user_options_user_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="user_id",
            new_name="user",
        ),
    ]
