# Generated by Django 6.0.7 on 2026-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.BigIntegerField(db_index=True, verbose_name='ID Мониторинга')),
                ('status', models.CharField(choices=[('OPEN', 'Открыт (Сайт лежит)'), ('RESOLVED', 'Решён (Сайт восстановился)')], db_index=True, default='OPEN', max_length=20, verbose_name='Текущий статус урла')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время начала аварии')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время восстановления')),
                ('cause', models.TextField(verbose_name='Информация по инциденту')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ['-started_at'],
            },
        ),
    ]
