# Generated by Django 6.0.7 on 2026-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID User-а'),
        ),
    ]
