apiVersion: v1
kind: Service
metadata:
  name: monitors
  namespace: uptime-monitor
spec:
  selector:
    app: monitors-web
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP