# Generated by Django 6.0.7 on 2026-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='ID Владельца')),
                ('receiver_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'Sms'), ('all', 'All')], db_index=True, default='email', max_length=20)),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('update', 'Update')], db_index=True, default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
