# Generated by Django 6.0.7 on 2026-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(default=0, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Заголовок/Тема'),
            preserve_default=False,
        ),
    ]
