global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Django-сервисы (при условии использования django-prometheus на эндпоинте /metrics)
  - job_name: 'django-apps'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'user_support_web:8001'
          - 'monitors_web:8002'
          - 'incidents_web:8003'
          - 'notifications_web:8004'

  # gRPC и асинхронные воркеры (если в них запущен prometheus_client)
  - job_name: 'grpc-services'
    static_configs:
      - targets:
          - 'user_support_grpc'
          - 'probes_grpc'