apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: uptime-monitor
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345678"
  POSTGRES_DB: "uptimemonitor"