# Generated by Django 6.0.7 on 2026-07-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название сервиса"),
                ),
                ("url", models.URLField(verbose_name="URL для проверки")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS  ", "OPTIONS"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="HTTP Метод",
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Интервал проверки (сек)"
                    ),
                ),
                (
                    "expected_status_code",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="Ожидаемый HTTP статус"
                    ),
                ),
                (
                    "expected_keyword",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ожидаемый текст в ответе",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Мониторинг активен"
                    ),
                ),
                (
                    "is_currently_up",
                    models.BooleanField(default=True, verbose_name="Сайт доступен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Монитор",
                "verbose_name_plural": "Мониторы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время проверки"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="HTTP статус"
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Время отклика (мс)"
                    ),
                ),
                ("is_success", models.BooleanField(verbose_name="Успешно?")),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст ошибки"
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="monitors.monitor",
                        verbose_name="Монитор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат проверки",
                "verbose_name_plural": "Результаты проверок",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-checked_at"],
                        name="monitors_ch_monitor_24c7e4_idx",
                    )
                ],
            },
        ),
    ]
