# Generated by Django 6.0.7 on 2026-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0, verbose_name="Сбоев подряд"),
        ),
    ]
