# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\xac\x01\n\x14UserSettingsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x18\n\x10telegram_chat_id\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x15\n\remail_enabled\x18\x05 \x01(\x08\x12\x18\n\x10telegram_enabled\x18\x06 \x01(\x08\x12\x13\n\x0bsms_enabled\x18\x07 \x01(\x08\x32]\n\x0bUserService\x12N\n\x1bGetUserNotificationSettings\x12\x12.users.UserRequest\x1a\x1b.users.UserSettingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=22
  _globals['_USERREQUEST']._serialized_end=52
  _globals['_USERSETTINGSRESPONSE']._serialized_start=55
  _globals['_USERSETTINGSRESPONSE']._serialized_end=227
  _globals['_USERSERVICE']._serialized_start=229
  _globals['_USERSERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
