# Generated by Django 6.0.7 on 2026-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='consecutive_successes',
            field=models.PositiveIntegerField(default=0, verbose_name='Корректных отработок подряд'),
        ),
    ]
